"""v1_6_managed_heroes

Revision ID: 06eaaa83af21
Revises: 3cbd1cecc618
Create Date: 2026-05-01 06:24:43.467164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06eaaa83af21'
down_revision: Union[str, None] = '3cbd1cecc618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing heroes default to managed=false (their players run their own
    # bot loops). New deploy-form heroes opt into managed=true.
    op.add_column('heroes', sa.Column('managed', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'managed')
    # ### end Alembic commands ###
