"""v0_8 journal entries

Revision ID: 2989d3beafaf
Revises: b91169b1e47e
Create Date: 2026-04-30 06:46:33.183382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2989d3beafaf'
down_revision: Union[str, None] = 'b91169b1e47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hero_id', sa.UUID(), nullable=False),
    sa.Column('tick_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_hero_id'), 'journal_entries', ['hero_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_tick_id'), 'journal_entries', ['tick_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_tick_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_hero_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
