"""v0_5 hero skills and equipped

Revision ID: 2a343aa68e74
Revises: b0bf5919708d
Create Date: 2026-04-29 20:01:14.235644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a343aa68e74'
down_revision: Union[str, None] = 'b0bf5919708d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with a server default so existing rows backfill cleanly.
    op.add_column('heroes', sa.Column('skills', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    op.add_column('heroes', sa.Column('equipped', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'equipped')
    op.drop_column('heroes', 'skills')
    # ### end Alembic commands ###
