"""v0_5_1 resource_nodes and recipes

Revision ID: 36da56b371ef
Revises: 2a343aa68e74
Create Date: 2026-04-29 20:07:19.300965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36da56b371ef'
down_revision: Union[str, None] = '2a343aa68e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('output_slug', sa.String(length=64), nullable=False),
    sa.Column('output_name', sa.String(length=120), nullable=False),
    sa.Column('output_kind', sa.String(length=32), nullable=False),
    sa.Column('output_description', sa.String(), nullable=False),
    sa.Column('output_props', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('skill_required', sa.String(length=32), nullable=False),
    sa.Column('skill_min', sa.Integer(), nullable=False),
    sa.Column('workstation_kind', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('resource_nodes',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('yield_item_slug', sa.String(length=64), nullable=False),
    sa.Column('yield_item_name', sa.String(length=120), nullable=False),
    sa.Column('yield_item_kind', sa.String(length=32), nullable=False),
    sa.Column('skill_required', sa.String(length=32), nullable=False),
    sa.Column('respawn_after_ticks', sa.Integer(), nullable=False),
    sa.Column('depleted_until_tick', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_resource_nodes_zone'), 'resource_nodes', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_nodes_zone'), table_name='resource_nodes')
    op.drop_table('resource_nodes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
