"""v1_5_hidden_recipes

Revision ID: 3cbd1cecc618
Revises: c858e54e2930
Create Date: 2026-04-30 21:54:52.054677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3cbd1cecc618'
down_revision: Union[str, None] = 'c858e54e2930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing recipes default to hidden=false (catalogued in /recipes).
    op.add_column('recipes', sa.Column('hidden', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'hidden')
    # ### end Alembic commands ###
