"""v1_1_2 trade_offers table

Revision ID: 41f6010a5d0f
Revises: 3c7e518f2ce5
Create Date: 2026-04-30 07:40:44.590424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41f6010a5d0f'
down_revision: Union[str, None] = '3c7e518f2ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_hero_id', sa.UUID(), nullable=False),
    sa.Column('to_hero_id', sa.UUID(), nullable=False),
    sa.Column('offered_items', sa.JSON(), nullable=False),
    sa.Column('offered_gold', sa.Integer(), nullable=False),
    sa.Column('wanted_items', sa.JSON(), nullable=False),
    sa.Column('wanted_gold', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at_tick', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_offers_from_hero_id'), 'trade_offers', ['from_hero_id'], unique=False)
    op.create_index(op.f('ix_trade_offers_to_hero_id'), 'trade_offers', ['to_hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_offers_to_hero_id'), table_name='trade_offers')
    op.drop_index(op.f('ix_trade_offers_from_hero_id'), table_name='trade_offers')
    op.drop_table('trade_offers')
    # ### end Alembic commands ###
