"""v1_0_1 npc persona and alignment

Revision ID: 49814a487a1b
Revises: 9ead8f605a9c
Create Date: 2026-04-30 07:12:48.934518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49814a487a1b'
down_revision: Union[str, None] = '9ead8f605a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('llm_persona', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('factions_aligned', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'factions_aligned')
    op.drop_column('npcs', 'llm_persona')
    # ### end Alembic commands ###
