"""v1_2 tournaments

Revision ID: 5e11642894c8
Revises: 41f6010a5d0f
Create Date: 2026-04-30 18:37:08.645390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e11642894c8'
down_revision: Union[str, None] = '41f6010a5d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_slug', sa.String(length=64), nullable=False),
    sa.Column('hero_id', sa.UUID(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('registered_at_tick', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_entries_hero_id'), 'tournament_entries', ['hero_id'], unique=False)
    op.create_index(op.f('ix_tournament_entries_tournament_slug'), 'tournament_entries', ['tournament_slug'], unique=False)
    op.create_table('tournaments',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at_tick', sa.Integer(), nullable=False),
    sa.Column('ends_at_tick', sa.Integer(), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=False),
    sa.Column('prize_gold', sa.Integer(), nullable=False),
    sa.Column('prize_faction', sa.String(length=32), nullable=True),
    sa.Column('prize_faction_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_tournament_entries_tournament_slug'), table_name='tournament_entries')
    op.drop_index(op.f('ix_tournament_entries_hero_id'), table_name='tournament_entries')
    op.drop_table('tournament_entries')
    # ### end Alembic commands ###
