"""v0_9 stash and buildings

Revision ID: 71391ad69298
Revises: 2989d3beafaf
Create Date: 2026-04-30 07:05:26.691382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71391ad69298'
down_revision: Union[str, None] = '2989d3beafaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_hero_id', sa.UUID(), nullable=True),
    sa.Column('gold_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_buildings_owner_hero_id'), 'buildings', ['owner_hero_id'], unique=False)
    op.create_index(op.f('ix_buildings_zone'), 'buildings', ['zone'], unique=False)
    op.add_column('items', sa.Column('stash_owner_hero_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_items_stash_owner_hero_id'), 'items', ['stash_owner_hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_stash_owner_hero_id'), table_name='items')
    op.drop_column('items', 'stash_owner_hero_id')
    op.drop_index(op.f('ix_buildings_zone'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_owner_hero_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
