"""v0_5_2 stacks and merchant stock

Revision ID: 862630dcba0d
Revises: 36da56b371ef
Create Date: 2026-04-29 20:10:37.724453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '862630dcba0d'
down_revision: Union[str, None] = '36da56b371ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('npcs', sa.Column('merchant_stock', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'merchant_stock')
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
