"""v0_4 baseline

Revision ID: b0bf5919708d
Revises: 
Create Date: 2026-04-29 19:56:03.581130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0bf5919708d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
