"""v0_7 pets factions quests

Revision ID: b91169b1e47e
Revises: c3127adf1881
Create Date: 2026-04-30 06:25:47.215742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b91169b1e47e'
down_revision: Union[str, None] = 'c3127adf1881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('count_required', sa.Integer(), nullable=False),
    sa.Column('reward_gold', sa.Integer(), nullable=False),
    sa.Column('reward_faction', sa.String(length=32), nullable=True),
    sa.Column('reward_faction_amount', sa.Integer(), nullable=False),
    sa.Column('offered_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hero_id', sa.UUID(), nullable=False),
    sa.Column('template_slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('count_done', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_hero_id'), 'quests', ['hero_id'], unique=False)
    op.add_column('heroes', sa.Column('faction_rep', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    op.add_column('npcs', sa.Column('tameable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('npcs', sa.Column('tamed_by_hero_id', sa.UUID(), nullable=True))
    op.add_column('npcs', sa.Column('quest_offered', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_npcs_tamed_by_hero_id'), 'npcs', ['tamed_by_hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npcs_tamed_by_hero_id'), table_name='npcs')
    op.drop_column('npcs', 'quest_offered')
    op.drop_column('npcs', 'tamed_by_hero_id')
    op.drop_column('npcs', 'tameable')
    op.drop_column('heroes', 'faction_rep')
    op.drop_index(op.f('ix_quests_hero_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_table('quest_templates')
    # ### end Alembic commands ###
