"""v0_6 magic

Revision ID: c3127adf1881
Revises: 862630dcba0d
Create Date: 2026-04-29 20:14:50.048067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3127adf1881'
down_revision: Union[str, None] = '862630dcba0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('school', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('mana_cost', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('damage_dice', sa.String(length=16), nullable=False),
    sa.Column('heal_dice', sa.String(length=16), nullable=False),
    sa.Column('skill_required', sa.String(length=32), nullable=False),
    sa.Column('skill_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.add_column('heroes', sa.Column('mana_max', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('heroes', sa.Column('mana_current', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('heroes', sa.Column('known_spells', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'known_spells')
    op.drop_column('heroes', 'mana_current')
    op.drop_column('heroes', 'mana_max')
    op.drop_table('spells')
    # ### end Alembic commands ###
