"""v1_4_bounties

Revision ID: c858e54e2930
Revises: f61ee8edf1fb
Create Date: 2026-04-30 21:49:52.050132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c858e54e2930'
down_revision: Union[str, None] = 'f61ee8edf1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_hero_id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(length=120), nullable=False),
    sa.Column('poster_hero_id', sa.UUID(), nullable=True),
    sa.Column('poster_name', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=280), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at_tick', sa.Integer(), nullable=False),
    sa.Column('claimed_by_hero_id', sa.UUID(), nullable=True),
    sa.Column('claimed_at_tick', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_poster_hero_id'), 'bounties', ['poster_hero_id'], unique=False)
    op.create_index(op.f('ix_bounties_target_hero_id'), 'bounties', ['target_hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bounties_target_hero_id'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_poster_hero_id'), table_name='bounties')
    op.drop_table('bounties')
    # ### end Alembic commands ###
