"""v1_3_lifespan_columns

Revision ID: f61ee8edf1fb
Revises: 5e11642894c8
Create Date: 2026-04-30 21:25:50.669360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f61ee8edf1fb'
down_revision: Union[str, None] = '5e11642894c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing heroes are backfilled to born_at_tick=0 — i.e. "they've been
    # alive since before we tracked it." The server_default lets the NOT NULL
    # constraint apply without a separate UPDATE step on existing rows.
    op.add_column('heroes', sa.Column('born_at_tick', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('heroes', sa.Column('died_at_tick', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_heroes_died_at_tick'), 'heroes', ['died_at_tick'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_died_at_tick'), table_name='heroes')
    op.drop_column('heroes', 'died_at_tick')
    op.drop_column('heroes', 'born_at_tick')
    # ### end Alembic commands ###
